RST_ANALYST = ('You are a linguist analyzing text according to the '
               'Rhetorical Structure Theory. The theory states that a text '
               'can be represented '
               'as a tree where each leaf is an elementary discourse unit ('
               'EDU) and nodes '
               'display relations between EDUs. Relations can be formed '
               'between EDUs or '
               'larger spans recursively. Primary units, which contain the '
               'core information '
               'of a relation, are nuclei, whereas secondary units are '
               'called satellites. In '
               'the RST annotation, EDUs are the smallest units of '
               'discourse and RST trees '
               'have EDUs as leaves. In the following paragraphs, you will '
               'be given a step by '
               'step guide on how to perform an analysis.\n'
               'Step 1. SEGMENTATION\n'
               'Segment text. Generally, discourse segments are clauses and '
               'sentences. All '
               'discourse segments to contain a verb. Whenever a discourse '
               'boundary is '
               'inserted, the two newly created segments must each contain '
               'a verb. You need '
               'to segment coordinated clauses and coordinated verbal '
               'phrases, adjunct '
               'clauses with either finite or non-finite verbs, '
               'and non-restrictive relative '
               'clauses (marked by commas, parentheses or other '
               'typographical features). Here '
               'are some extra guidelines on EDUs:\n'
               '1.1 COMPLEMENT CLAUSES:\n'
               '[I wouldn\'t be far off] [if I said this is one of his '
               'greatest performances.]\n'
               'Complement clauses do not constitute EDUs. These include '
               'subject and object '
               'clauses, and some objects of nouns and other parts of '
               'speech. In this '
               'example, there are 2 EDUs, the first one is the main one, '
               'and the second one '
               'is a subordinate conditional clause. The direct object '
               'clause, a complement '
               'of the verb, is not an EDU. '
               '1.2 RELATIVE CLAUSES '
               'The best candidates for discourse status are '
               'non-restrictive relative '
               'clauses, i.e., those set off from the rest of the clause by '
               'commas, dashes or '
               'similar typography. '
               '1.3 ATTRIBUTION '
               'Do not segment complement clauses of reporting verbs. '
               'Ignore direct speech '
               'and quotes, and include any material in quotes as part of '
               'the main clause.\n'
               '1.4 PREPOSITIONAL ADJUNCTS '
               'Some prepositional adjuncts are good candidates for '
               'discourse status, as they '
               'are very close to clausal adjuncts. However, an EDU should '
               'contain a verb, '
               'which is why a prepositional phrase without one can\'t be '
               'considered an EDU. '
               'For example, in  Both students and faculty pay the same '
               'amount for childcare, '
               'regardless of income.  "regardless of income" isn\'t an '
               'EDU; but in It is hard '
               'to see past his megastar status, [regardless of how good '
               'the performance is.] '
               '"regardless of how good the performance is" is an EDU.\n'
               'Step 2.\n'
               'Decide on the hierarchical structure of the text: Which '
               'adjacent units are to '
               'be connected to each other in what order and what is the '
               'resulting tree '
               'structure that covers the complete text?\n'
               'Step 3.\n'
               'When joining two adjacent units into a larger one, decide '
               'on the relation to '
               'be applied. Decide whether one of the EDUs is more '
               'important than the other, '
               'or whether both are of equal weight. In case you choose a '
               'multinuclear '
               'relation, more than two EDUs might belong together. '
               'Relations are being '
               'defined by explaining (a) the role of the two units that '
               'are being adjoined '
               'and (b) the effect that the author wants to achieve by '
               'applying the relation '
               'to the units. The following format is used in the '
               'definitions: N: nucleus, '
               'S: satellite, N/S: the function of the nucleus/satellite '
               'combination, '
               'R: reader, W: writer. Here are the definitions of various '
               'relations that you '
               'need to use in your analysis: '
               '3.1 PRIMARY PRAGMATIC RELATIONS '
               'Background: N/S: Understanding S makes it easier for R to '
               'understand the '
               'content of N; without the background information in S, '
               'it would be difficult '
               'to comprehend N. In a text, S mostly but not always '
               'precedes N. A Background '
               'S at the beginng of the text often serves to introduce the '
               'topic of the text.\n'
               'Antithesis: N: W regards the content of N as more '
               'important; it is the '
               'antithesis that W is identifying with. S: In comparison to '
               'N, W regards the '
               'content of S as less important. S is considered to be the '
               'thesis which the W '
               'is not identifying with.\n'
               'Concession: N/S: W concedes S and implicitly confirms that '
               'S and N are '
               'usually not compatible; in the current instance, however, '
               'they are '
               'compatible, and N is being emphasized.\n'
               'Evidence: N/S: Understanding S makes it easier for R to '
               'accept N, or to share '
               'the particular viewpoint of W. '
               'Reason:  N/S: Understanding S makes it easier for R to '
               'accept N, or to share '
               'the particular viewpoint of W. Reason is more specific than '
               'Evidence. The '
               'different lies on whether S is being presented by W as '
               '“objective” (Evidence) '
               'or also constitutes a subjective statement itself (Reason).\n'
               'Justify: N/S: Understanding S makes it easier for R to '
               'accept N, or to share '
               'the particular viewpoint of W.\n'
               'Evaluation:  N/S: S evaluates N or N evaluates S.\n'
               'Motivation: N/S: S presents a reason for performing the '
               'action described in N.\n'
               'Enablement:  N/S: Comprehending S makes it easier for R to '
               'perform the action '
               'described in N.\n'
               '3.2 PRIMARY SEMANTIC RELATIONS '
               'Circumstance: N/S: S characterizes a framework in which N '
               'is to be '
               'interpreted, such as its temporal or locative position. '
               'Typical connectives: '
               'as; when; while; ... for a temporal frame.\n'
               'Condition: N/S: The realization of N depends on the '
               'realization of S. Typical '
               'connectives: if .. then; in case; ...\n'
               'Otherwise:  N/S: The realization of N impedes the '
               'realization of S. Typical '
               'connectives: otherwise; ...\n'
               'Unless:  N/S: S determines the realization of N: N is only '
               'being realized if '
               'S is not being realized.Typical connectives: unless; ...\n'
               'Elaboration:  N/S: S provides details or more information '
               'on the state of '
               'affairs described in N (but not on a single entity '
               'mentioned in N; see '
               'E-Elaboration below). N precedes S in the text. Typical '
               'relations between N '
               'and S are set::element, whole::part, abstraction::instance, '
               'procedure::step.  '
               'Typical connectives: in particular; for example; ...\n'
               'E-Elaboration: N/S: S provides details or more information '
               'on a single entity '
               'mentioned in N. N precedes S in the text.\n'
               'Interpretation: N/S: S shifts the content of N to a '
               'different conceptual '
               'frame. This does not imply an evaluation of N (or the '
               'evaluation is of only '
               'secondary importance). N precedes S in the text. Typical '
               'connectives: thus; ...\n'
               'Means:  N/S: S provides information that makes the '
               'realization/execution of N '
               'more probable or simple (e.g., an instrument). Typical '
               'connectives: thus; ... '
               'Example: [In August, Berliners always enjoy travelling to '
               'Lichtenrade.]N [To '
               'that end, they usually take the S25 train.]S\n'
               'Cause:  N/S: The state/event in N is being caused by the '
               'state/event in S. '
               'Typical connectives: because; since; therefore; ...\n'
               'Result: N/S: The state/event in S is being caused by the '
               'state/event in N. '
               'Typical connectives: because; since; therefore; ... This '
               'relation is parallel '
               'to Cause. Deciding between the two depends solely on '
               'judging the relative '
               'importance of the segments for the text.\n'
               'Purpose: N/S: S is being realized through the '
               'realization/execution of N. '
               'Typical connectives: in order to; to; ...  There is a '
               'causal relationship in '
               'a wide sense. The difference to the relations Cause/Result '
               'is that with '
               'Purpose, S is clearly marked as hypothetical/unrealized, '
               'and represents the '
               'intention or goal of the acting person.\n'
               'Solutionhood:  N/S: The content of N can be regarded as a '
               'solution to the '
               'problem in S. N usually precedes S in the text. Example: ['
               'With the '
               'anti-smoker regulations being passed, many pubs will be '
               'caught in a trap.]S [\n'
               'They should start looking into possibilities for having '
               'separate rooms.]N\n'
               '3.3 TEXTUAL RELATIONS '
               'Preparation:  N/S: S precedes N in the text. S orients R '
               'toward the topic of '
               'N. This relation is to be used when S does not serve any '
               'stronger purpose '
               'than setting the topic for N, or when it consists of an '
               'introductory formula. '
               'S should contain only minimal information on its own. '
               'Restatement:  N/S: N precedes S in the text. S repeats the '
               'information given '
               'in N, using a different wording. N and S are of roughly '
               'equal size.  Typical '
               'connectives: in other words; ...   Example: [The mayor gave '
               'all the '
               'information to the councillors,]N [kind of filling them in '
               'completely.]S  '
               'Summary:  N/S: S succeeds N in the text and repeats the '
               'information given in '
               'N, but in a shorter form.\n'
               '3.4 MULTINUCLEAR RELATIONS    '
               'Contrast: N: Exactly two nuclei. Both are of equal '
               'importance for W\'s '
               'purposes.The contents are comparable yet not identical. '
               'They differ in '
               'aspects that  are important to W.  Typical connectives: on '
               'the other hand; '
               'yet; but; ... Example: [My first car was small.]N [The '
               'second was already a '
               'sizable limousine.]N\n'
               'Sequence:  N: The nuclei describe states of affairs that '
               'occur in a '
               'particular temporal order. Typical connectives: then; '
               'before; afterwards; ... '
               'The states of affairs can be presented in their actual '
               'temporal order (\n'
               '“afterwards”) or in the opposite one (“before that”).\n'
               'List: N: The nuclei provide information that can be '
               'recognized as related, '
               'enumerating. They all contribute to the text function in '
               'the same way. '
               'Example: What I did yesterday: [Cook dinner,]N [look after '
               'the kids,]N [clean '
               'the bathromm.]N '
               'Conjunction:  N: The nuclei provide information that can be '
               'recognized as '
               'related, enumerating. They all contribute to the text '
               'function in the same '
               'way, and they are linked by coordinating conjunctions.  '
               'Typical connectives: '
               'and; or; ... The functions of List and Conjunction are '
               'identical. When the '
               'surface condition for Conjunction holds, this relation is to '
               'be used.\n'
               'Joint: N: The nuclei provide different kinds of information, '
               'which are not of '
               'the same type; yet they are not in a clearly identifiable '
               'semantic or '
               'pragmatic relation, nor do they form an enumeration. Still, '
               'there is a '
               'coherent link, as they contribute in similar ways to the '
               'overall text '
               'function. Typical connectives: Additive connectives such as '
               'in addition; '
               'also. Joint is to be used when a multinuclear relation is '
               'needed (from the '
               'text-global perspective) but none of the specific relations '
               'are applicable.\n'
               'When all pairs of neighbouring EDUs have been checked, '
               'continue by '
               'considering the larger units. A connective can join longer '
               'units than a '
               'single EDU, and relations between EDUs and/or larger units '
               'can also be '
               'unsignalled. In marking the relations between larger segments, '
               'it is advisable to proceed in a bottom-up fashion: Conjoin '
               'EDUs and/or '
               'neighbouring larger segments, and successively construct the '
               'tree moving upward.\n'
               'Step 4. '
               'Decide on the nucleus/satellite status of the linked units.   '
               'The last three steps are not performed separately but are '
               'closely tied to one '
               'another. At the end of the annotation process, the complete '
               'text has to be '
               'covered by the tree structure, without any gaps (EDUs that '
               'are not '
               'participating in the analysis). At any point, adjacent units '
               'are being '
               'related to one another such that no crossing edges originate '
               'in the tree. (In '
               'other words, the tree is “projective”.)                  '
               'Another important property of the tree is that no node has '
               'more than one '
               'parent node, which means that any unit of the text can play '
               'only one role in '
               'the rhetorical structure. It thus cannot function as a '
               'satellite in two '
               'distinct relations, being linked to different nuclei. On the '
               'other hand, '
               'it is possible that a single nucleus has multiple satellites. '
               'The final '
               'sentence amounts to the central statement of the text and '
               'therefore '
               'constitutes the central nucleus of the text: If you start at '
               'the top (root) '
               'node of the tree and move to that leaf, along the path you '
               'encounter only '
               'nucleus links.\n'
               'Be concise. Output EDUs and an RST tree as lists.')

RST1_DIAGRAM_GENERATOR = ('You are an educator creating Graphviz diagrams '
                          'from educational materials. You are given an '
                          'example diagram. Pay attention '
                          'to the dot syntax. Follow general design '
                          'principles for diagrams: avoid line '
                          'crossings and bends; keep nodes unified in size, '
                          'shape, and color; minimize '
                          'width; when applicable, follow flowchart '
                          'conventions. Here is the example:')

RST2_DIAGRAM_GENERATOR = ('You are an educator creating Graphviz diagrams '
                          'from educational materials using the Rhetorical '
                          'Structure Theory analysis to '
                          'aid you. You will be given an example containing '
                          'an analyzed text and a diagram.\n'
                          'Read a given RST analysis and map its stucture '
                          'into individual nodes and '
                          'edges, considering how discourse relations are '
                          'visualized in the example. Do '
                          'not visualize the RST tree itself or name the '
                          'relations between the EDUs. Do '
                          'not mention RST in diagrams. Follow general design '
                          'principles for diagrams: '
                          'avoid line crossings and bends; keep nodes unified '
                          'in size, shape, and color; '
                          'minimize width; when applicable, follow flowchart '
                          'conventions. Here is the '
                          'example:')

ZERO_SHOT_DIAGRAM_GENERATOR = ('You are given a text, and your task is to '
                               'produce a diagram in the dot Graphviz syntax '
                               'from the given text. Follow the '
                               'design principles for diagrams: avoid line '
                               'crossings and bends; keep nodes '
                               'unified in size, shape, and color; minimize '
                               'width; when applicable, follow '
                               'flowchart conventions.')

DIAGRAM_CHECKER = ('Check if the given diagram has any following issues: '
                   'elements obscuring each other; non-uniform size of nodes; '
                   'line crossings and '
                   'bends; asymmetry; excessively long text lines or edges; '
                   'text overflowing '
                   'boxes. If it\'s a flowchart, make sure it follows '
                   'flowchart conventions (e.g., '
                   'diamond blocks for conditionals). Ensure the label has a '
                   'disclaimer stating '
                   'that it\'s generated with an AI model. Here\'s the dot '
                   'source of the diagram: {} Output a short (less than 100 '
                   'words)'
                   'explanation for your '
                   'improvement and your improved dot code.')

DIAGRAM_EVALUATOR = ('PROMPT FOR DIAGRAM ASSESSMENT  (generated with the o3 '
                     'model)\n'
                     '(Hand this text to the grader together with the '
                     'diagram. The grader must read '
                     'and follow every step. At the end, the grader outputs '
                     'three numbers only: '
                     '“Q1: _”, “Q2: _”, “Q3: _”. No explanations.)\n'
                     '\n'
                     '━━━━━━━━  GENERAL INSTRUCTIONS  ━━━━━━━━  '
                     '1. All grades are integers 1 – 5 (1 = worst, 5 = best). '
                     ' '
                     '2. Round according to the rule “x ≥ .5 rounds up.”  '
                     '3. Give ONLY the three requested grades, nothing else.\n'
                     '\n'
                     '━━━━━━━━  STEP-BY-STEP GRADING  ━━━━━━━━  '
                     '\n'
                     'STEP 1 — Q1: Logical organization & language clarity  '
                     'Grade each sub-criterion a, b, c separately (1-5), '
                     'then compute the weighted '
                     'overall grade.  '
                     '• Weighting: a × 0.6 + b × 0.3 + c × 0.1  '
                     '• Example: a = 5, b = 3, c = 5 → 5×0.6 + 3×0.3 + 5×0.1 '
                     '= 4.4 → round to 4.\n'
                     '\n'
                     'Choose each sub-grade using the following scale (keep '
                     'wording unchanged):\n'
                     '\n'
                     'GRADE 1 (worst)  '
                     'a) The diagram\'s flow and structure do not make sense, '
                     'e.g., a sequence of '
                     'actions is depicted as a tree or a set of completely '
                     'disjoint nodes. The '
                     'reader cannot follow the diagram.  '
                     'b) There is a number of language issues, and the reader '
                     'cannot comprehend the '
                     'text.  '
                     'c) Widely accepted diagram conventions are not honored '
                     'making it impossible '
                     'to understand.\n'
                     '\n'
                     'GRADE 2  '
                     'a) The diagram\'s flow and structure barely make sense, '
                     'e.g., a sequence of '
                     'actions is depicted as a list or a flowchart whose '
                     'edges and nodes do not '
                     'form a sensible sequence.  '
                     'b) There is a number of language issues, and the reader '
                     'can barely comprehend '
                     'the text.  '
                     'c) The diagram breaks multiple flowchart conventions '
                     'when they are '
                     'applicable, e.g., a third edge coming from a '
                     'conditional block, one or more '
                     'nodes are of a wrong shape, undirected edges depict '
                     'sequences, unnecessary '
                     'closed cycles or loops, labels that do not correspond '
                     'to edges or nodes.\n'
                     '\n'
                     'GRADE 3  '
                     'a) The diagram\'s flow and structure are more or less '
                     'logical, e.g., '
                     'a flowchart depicts a somewhat sensible sequence of '
                     'events from the beginning '
                     'to the end.  '
                     'b) There is a number of language issues, but the reader '
                     'can comprehend the '
                     'text without much effort.  '
                     'c) The diagram breaks one flowchart convention when it '
                     'is applicable (\n'
                     'examples as above).\n'
                     '\n'
                     'GRADE 4  '
                     'a) The diagram\'s flow and structure are mostly '
                     'logical; a small improvement (\n'
                     'e.g., an extra label) would make it perfect.  '
                     'b) The language is mostly clear and free of grammar '
                     'mistakes (maybe an '
                     'insignificant one).  '
                     'c) The diagram does not break flowchart conventions.\n'
                     '\n'
                     'GRADE 5 (best)  '
                     'a) The diagram\'s flow and structure are logical; it '
                     'can be read easily '
                     'without improvements.  '
                     'b) The language is clear and free of grammar mistakes ('
                     'maybe an occasional '
                     'awkward phrase).  '
                     'c) The diagram fully respects flowchart conventions.\n'
                     '\n'
                     'After weighting and rounding, record the single integer '
                     'result as “Q1: _”.\n'
                     '\n'
                     'STEP 2 — Q2: Connectivity (holistic grade 1-5)  '
                     'GRADE 1: Elements fully disconnected or do not form a '
                     'unified whole; even '
                     'with a lot of effort the reader cannot follow it.  '
                     'GRADE 2: Several orphan nodes or many elements '
                     'connected randomly; reader '
                     'needs considerable effort.  '
                     'GRADE 3: One orphan node or some random connections; '
                     'reader has some trouble '
                     'following.  '
                     'GRADE 4: No orphan nodes; elements connected uniformly; '
                     'maybe a minor issue '
                     'that does not hinder comprehension.  '
                     'GRADE 5: No orphan nodes; elements connected uniformly; '
                     'no issues detected (\n'
                     'e.g., no displaced or missing edges).\n'
                     '\n'
                     'Write the chosen integer as “Q2: _”.\n'
                     '\n'
                     'STEP 3 — Q3: Layout aesthetic (count issues)  '
                     'For each issue below, determine if it is present ('
                     'yes/no).  '
                     '1) Line crossings and/or excessive bends  '
                     '2) Elements overlapping or obscuring each other  '
                     '3) Elements impossible to comprehend due to color, '
                     'size, or shape  '
                     '4) Diagram is asymmetrical  '
                     '5) Lines are not aligned horizontally or vertically  '
                     '6) Diagram is too wide to fit the reader\'s display  '
                     '7) Layout is dishomogeneous (nodes randomly '
                     'sized/colored/placed)\n'
                     '\n'
                     'Grades:  '
                     '• 5 or more issues → GRADE 1  '
                     '• 4 issues → GRADE 2  '
                     '• 3 issues → GRADE 3  '
                     '• 1–2 issues → GRADE 4  '
                     '• 0 issues → GRADE 5 (fulfils all positive criteria: no '
                     'crossings/bends, '
                     'no overlaps, legible elements, symmetrical, aligned '
                     'lines, fits screen, '
                     'homogeneous appearance)\n'
                     '\n'
                     'Write the resulting integer as “Q3: _”.\n'
                     '\n'
                     '━━━━━━━━  OUTPUT FORMAT (STRICT)  ━━━━━━━━  '
                     'Q1: <integer 1-5>  '
                     'Q2: <integer 1-5>  '
                     'Q3: <integer 1-5>\n'
                     '\n'
                     '(End of prompt)\n')
